source 'https://rubygems.org' do
  gem 'sinatra' # DSL web framework
  gem 'toml-rb' # Read TOML files
  gem 'mysql2' # Connect to mysql db
  gem 'nokogiri' # parse HTML
  gem 'net-sftp' # connect to sftp servers
  gem 'selenium-webdriver' # headless web browsing with Chrome
  #gem 'sinatra-contrib' # used for sinatra/json, but didn't set the encoding
  group :production do
    gem 'puma' # production web server
  end
  group :development do
    gem 'rerun' # Restart app server when files change
    gem 'pry' # Set breakpoints in Ruby code; Ruby console
  end
end
